from __future__ import annotations

TEXT = {
    # Common
    "display_mode": "表格顯示模式",
    "no_export_data": "目前沒有可匯出的資料",
    "download_csv": "匯出 CSV",
    "select_store": "選擇分店",
    "select_vendor": "選擇廠商",
    "select_item": "選擇品項",
    "date": "日期",
    "start_date": "起始日期",
    "end_date": "結束日期",
    "back": "返回",
    "back_to_menu": "返回選單",
    "back_to_function_menu": "返回功能選單",
    "mobile_simple": "手機精簡",
    "full_report": "完整表格",

    # Reports
    "title_stock_order_compare": "庫存 + 叫貨對照表",
    "title_view_history": "歷史叫貨紀錄",
    "title_export": "資料匯出",
    "title_analysis": "進銷存分析",
    "title_cost_debug": "成本檢查",
    "need_select_store": "請先選擇分店",
    "no_data_today": "這一天沒有可顯示的資料",
    "no_non_zero_data_today": "這一天沒有非 0 的庫存 / 叫貨資料",
    "no_data_current_condition": "此條件下沒有可顯示的資料",
    "label_vendor_filter": "選擇廠商",
    "label_export_type": "匯出資料類型",
    "export_today_purchase_detail": "今日進貨明細",
    "export_analysis": "進銷存分析",
    "export_history": "歷史叫貨紀錄",
    "no_export_store_data": "目前沒有可匯出的分店資料",
    "analysis_no_records": "此區間內查無紀錄。",
    "analysis_all_vendor_summary": "全部廠商金額統計",
    "analysis_vendor_detail": "品項明細",
    "current_condition_no_amount": "目前沒有可顯示的金額資料",
    "current_vendor_no_data": "此廠商在目前條件下無資料",
    "current_vendor_no_item_data": "此廠商在目前條件下無品項資料",
    "metric_total_purchase": "進貨總金額",
    "metric_total_stock": "庫存總金額",
    "history_no_record": "此區間內無紀錄。",
    "history_no_data": "此條件下無歷史資料",
    "history_all_vendor_hide": "全部廠商時，歷史叫貨紀錄明細預設不顯示",
    "history_vendor_filter": "選擇廠商",
    "history_item_filter": "選擇品項",
    "cost_debug_items_fail": "items 資料讀取失敗",
    "cost_debug_query_date": "查詢日期",
    "cost_debug_result": "檢查結果",
    "cost_debug_conversion": "換算規則",
    "cost_debug_no_conversion": "此品項目前沒有換算規則",
    "item_name": "品項名稱",
    "base_unit": "基準單位",
    "default_stock_unit": "預設庫存單位",
    "default_order_unit": "預設叫貨單位",
    "price": "價格",
    "price_unit": "價格單位",
    "effective_date": "價格生效日",
    "base_unit_cost": "基準單位成本",
    "not_set": "未設定",
    "cannot_calculate": "無法計算",

    # User admin
    "title_user_admin": "使用者權限",
    "no_access_user_admin": "你沒有權限進入此頁。",
    "tab_user_list": "使用者列表",
    "tab_account_edit": "帳號編輯",
    "tab_store_permission": "分店權限",
    "tab_promotion": "升遷與角色調整",
    "tab_role_permission": "角色權限表",
    "user_list": "使用者列表",
    "no_user_data": "目前尚無使用者資料",
    "account": "帳號",
    "name": "名稱",
    "role": "角色",
    "store": "分店",
    "status": "狀態",
    "last_login": "最後登入",
    "quick_manage": "快速管理",
    "no_manageable_users": "目前沒有可管理的使用者",
    "select_user": "選擇使用者",
    "reset_password_123456": "重設密碼為 123456",
    "reset_password_success": "已重設密碼為 123456，且下次登入需強制修改。",
    "action_failed": "操作失敗",
    "update_failed": "更新失敗",
    "disable_account": "停用帳號",
    "enable_account": "啟用帳號",
    "account_status_updated": "帳號狀態已更新。",
    "current_status": "目前狀態",
    "add_user": "新增使用者",
    "no_available_roles": "目前 roles 表沒有可用角色，無法新增使用者。",
    "login_account": "登入帳號",
    "display_name": "顯示名稱",
    "role_name": "角色",
    "store_name": "分店",
    "placeholder_account": "例如：staff01",
    "placeholder_name": "例如：阿辰",
    "default_password": "預設密碼：123456",
    "change_password_first_login": "建立後，使用者第一次登入會被要求修改密碼。",
    "create_user_button": "建立使用者",
    "please_enter_account": "請輸入帳號。",
    "please_enter_name": "請輸入名稱。",
    "account_exists": "此帳號已存在，請改用其他帳號。",
    "role_requires_store": "此角色必須綁定指定分店，不可使用全部分店。",
    "store_manager_limit_reached_create": "此分店店長已達 3 位上限，請先調整後再建立。",
    "create_success": "建立成功。預設密碼為 123456，第一次登入需修改密碼。",
    "create_failed": "建立失敗",
    "edit_existing_user": "編輯既有使用者",
    "no_editable_users": "目前沒有可編輯的使用者",
    "select_edit_user": "選擇要編輯的使用者",
    "active": "啟用",
    "inactive": "停用",
    "edit_user_button": "更新使用者",
    "store_manager_limit_reached_update": "此分店店長已達 3 位上限，無法更新。",
    "user_updated": "使用者資料已更新。",
    "store_permission_management": "分店權限管理",
    "manager_management": "店長管理",
    "no_manager_data": "目前沒有店長資料",
    "manager_account": "店長帳號",
    "manager_name": "店長名稱",
    "manager_store": "所屬分店",
    "select_manager": "選擇店長",
    "reassign_store": "改派分店",
    "update_manager_store": "更新店長分店",
    "store_manager_limit_assign": "此分店店長已達 3 位上限，無法再指派。",
    "manager_store_updated": "店長分店已更新。",
    "leader_management": "組長管理",
    "no_leader_data": "目前沒有組長資料",
    "leader_account": "組長帳號",
    "leader_name": "組長名稱",
    "select_leader": "選擇組長",
    "update_leader_store": "更新組長分店",
    "leader_store_updated": "組長分店已更新。",
    "promotion_title": "升遷與角色調整",
    "promotion_caption": "這一區用來做既有使用者的角色調整，並同步留下 audit 記錄。",
    "no_promotion_target": "目前沒有可調整角色的使用者",
    "select_employee": "選擇員工",
    "current_role": "目前角色",
    "new_role": "調整為新角色",
    "sync_store": "同步調整分店",
    "note": "備註",
    "note_placeholder": "例如：升任組長 / 調店 / 權限調整",
    "role_unchanged": "角色不變",
    "promotion_up": "升遷",
    "promotion_down": "降階 / 角色下調",
    "current_judgment": "本次判定",
    "submit_role_change": "送出角色調整",
    "store_manager_limit_promotion": "此分店店長已達 3 位上限，無法調整。",
    "role_change_done": "角色調整完成。",
    "role_permission_table": "角色權限表",
    "role_permission_caption": "此頁以顯示制度為主，讓管理者可快速對照各角色可見功能。",
    "supplement": "補充說明",
    "permission_note_1": "- 權限控制以 role + store_scope + is_active 為主，不使用複雜 ACL。",
    "permission_note_2": "- 成本檢查僅限 Owner / Admin 可見。",
    "permission_note_3": "- 店長與組長必須綁定指定分店，不可使用全部分店。",
    "permission_note_4": "- 每店啟用中的店長上限為 3 位。",
    "all_stores": "全部分店",
    "unknown": "未設定",
}

def t(key: str, default: str | None = None) -> str:
    return TEXT.get(key, default if default is not None else key)
